# doc.yml
# ドキュメント生成・チェック用ワークフロー

name: Docs

on:
  push:
    paths:
      - "README.md"
      - "docs/**"
      - "**.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Markdown Lint
        run: |
          npx markdownlint-cli2 '**/*.md' || true
