# main.yml
# プッシュ・プルリクエスト時にCIを実行する基本ワークフロー

name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies (Python)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install dependencies (Node.js)
        run: |
          if [ -f package.json ]; then npm install; fi
      - name: Run tests (Python)
        run: |
          if [ -f requirements.txt ]; then pytest || true; fi
      - name: Run tests (Node.js)
        run: |
          if [ -f package.json ]; then npm test || true; fi
      - name: Run C++ tests (Google Test)
        run: |
          find . -name "*_test.cpp" | xargs -r -I{} g++ -std=c++17 -isystem /usr/include/gtest -pthread {{}} -lgtest -lgtest_main -o test_bin && ./test_bin || true
        shell: bash
